[package]
name = "napi"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
encoding_rs = "0.8.35"
md5 = "0.8.0"
sevenz-rust2 = "0.19"
testresult = "0.4.1"
hex = "0.4.3"
reqwest = { version = "0.12.24", features = ["blocking"] }

[dev-dependencies]
